sonar.projectKey=insurance-new
sonar.projectName=Insurance New
sonar.projectVersion=1.0

sonar.sources=backend/src/main/java,frontend/src
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/.angular/**

sonar.java.binaries=backend/target/classes
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.tsconfigPath=frontend/tsconfig.json
